#include "../common/logger.h"
#include "../common/module.h"
#include "globalvar.h"
#include "algorithm.h"
#include "canalasku_data.h"

// ----------------------------------------------------------------------------
void AskuAlgorithm::prepareMessages()
{
	messages["124yy08@mest"].setMessage("*:mest", "switch", "124УУ08", "Режим работы - местное управление");
	messages["124yy08@mest"].setMessage("mest:norma", "switch", "124УУ08", "Режим работы - дистанционное управление");
	messages["124yy08@d2vv056"].setMessage("*:avar", "avar", "124УУ08", "Д2ВВ056 - авария");
	messages["124yy08@d2vv056"].setMessage("avar:norma", "norma", "124УУ08", "Д2ВВ056 - норма");
	messages["124yy08@123yy01"].setMessage("*:avar", "avar", "124УУ08", "123УУ01 - авария");
	messages["124yy08@123yy01"].setMessage("avar:norma", "norma", "124УУ08", "123УУ01 - норма");

	messages["124yg02@mest1"].setMessage("*:mest", "switch", "124УГ02", "Режим работы - местное управление (ПРД 1)");
	messages["124yg02@mest1"].setMessage("mest:norma", "switch", "124УГ02", "Режим работы - дистанционное управление (ПРД 1)");
	messages["124yg02@mest2"].setMessage("*:mest", "switch", "124УГ02", "Режим работы - местное управление (ПРД 2)");
	messages["124yg02@mest2"].setMessage("mest:norma", "switch", "124УГ02", "Режим работы - дистанционное управление (ПРД 2)");
	messages["124yg02@d2vv056_1"].setMessage("*:avar", "avar", "124УГ02", "Д2ВВ056(1) - авария");
	messages["124yg02@d2vv056_1"].setMessage("avar:norma", "norma", "124УГ02", "Д2ВВ056(1) - норма");
	messages["124yg02@d2vv056_2"].setMessage("*:avar", "avar", "124УГ02", "Д2ВВ056(2) - авария");
	messages["124yg02@d2vv056_2"].setMessage("avar:norma", "norma", "124УГ02", "Д2ВВ056(2) - норма");
	messages["124yg02@123yy01"].setMessage("*:avar", "avar", "124УГ02", "123УУ01 - авария");
	messages["124yg02@123yy01"].setMessage("*:error", "error", "124УГ02", "123УУ01 - авария");
	messages["124yg02@123yy01"].setMessage("avar,error:norma", "norma", "124УГ02", "123УУ01 - норма");

	messages["prd_control_panel@qf_123gv02_1"].setMessage("*:avar", "avar", "125УУ04", "QF 123ГВ02-1 - отключен");
	messages["prd_control_panel@qf_123gv02_1"].setMessage("avar:norma", "norma", "125УУ04", "QF 123ГВ02-1 - включен");
	messages["prd_control_panel@qf_123gv02_2"].setMessage("*:avar", "avar", "125УУ04", "QF 123ГВ02-2 - отключен");
	messages["prd_control_panel@qf_123gv02_2"].setMessage("avar:norma", "norma", "125УУ04", "QF 123ГВ02-2 - включен");
	messages["prd_control_panel@qf_123bb01_1"].setMessage("*:avar", "avar", "125УУ04", "QF 123ББ01-1 - отключен");
	messages["prd_control_panel@qf_123bb01_1"].setMessage("avar:norma", "norma", "125УУ04", "QF 123ББ01-1 - включен");
	messages["prd_control_panel@qf_123bb01_2"].setMessage("*:avar", "avar", "125УУ04", "QF 123ББ01-2 - отключен");
	messages["prd_control_panel@qf_123bb01_2"].setMessage("avar:norma", "norma", "125УУ04", "QF 123ББ01-2 - включен");
	messages["prd_control_panel@qf_123bb01_3"].setMessage("*:avar", "avar", "125УУ04", "QF 123ББ01-3 - отключен");
	messages["prd_control_panel@qf_123bb01_3"].setMessage("avar:norma", "norma", "125УУ04", "QF 123ББ01-3 - включен");
	messages["prd_control_panel@qf_123bb01_4"].setMessage("*:avar", "avar", "125УУ04", "QF 123ББ01-4 - отключен");
	messages["prd_control_panel@qf_123bb01_4"].setMessage("avar:norma", "norma", "125УУ04", "QF 123ББ01-4 - включен");
	messages["prd_control_panel@qf_126gg02_1"].setMessage("*:avar", "avar", "125УУ04", "QF 126ГГ02-1 - отключен");
	messages["prd_control_panel@qf_126gg02_1"].setMessage("avar:norma", "norma", "125УУ04", "QF 126ГГ02-1 - включен");
	messages["prd_control_panel@qf_126gg02_2"].setMessage("*:avar", "avar", "125УУ04", "QF 126ГГ02-2 - отключен");
	messages["prd_control_panel@qf_126gg02_2"].setMessage("avar:norma", "norma", "125УУ04", "QF 126ГГ02-2 - включен");
	messages["prd_control_panel@qf_chp_1"].setMessage("*:avar", "avar", "125УУ04", "QF ЧП-1 - отключен");
	messages["prd_control_panel@qf_chp_1"].setMessage("avar:norma", "norma", "125УУ04", "QF ЧП-1 - включен");
	messages["prd_control_panel@qf_chp_2"].setMessage("*:avar", "avar", "125УУ04", "QF ЧП-2 - отключен");
	messages["prd_control_panel@qf_chp_2"].setMessage("avar:norma", "norma", "125УУ04", "QF ЧП-2 - включен");
	messages["prd_control_panel@qf_chp_3"].setMessage("*:avar", "avar", "125УУ04", "QF ЧП-3 - отключен");
	messages["prd_control_panel@qf_chp_3"].setMessage("avar:norma", "norma", "125УУ04", "QF ЧП-3 - включен");
	messages["prd_control_panel@qf_chp_4"].setMessage("*:avar", "avar", "125УУ04", "QF ЧП-4 - отключен");
	messages["prd_control_panel@qf_chp_4"].setMessage("avar:norma", "norma", "125УУ04", "QF ЧП-4 - включен");

	messages["prd_control@123gv02_1"].setMessage("*:avar", "avar", "125УУ04", "ПУМ 123ГВ02-1 - авария");
	messages["prd_control@123gv02_1"].setMessage("*:norma", "norma", "125УУ04", "ПУМ 123ГВ02-1 - норма");
	messages["prd_control@123gv02_1"].setMessage("*:not", "norma", "125УУ04", "ПУМ 123ГВ02-1 - отключен");
	messages["prd_control@123gv02_2"].setMessage("*:avar", "avar", "125УУ04", "ПУМ 123ГВ02-2 - авария");
	messages["prd_control@123gv02_2"].setMessage("*:norma", "norma", "125УУ04", "ПУМ 123ГВ02-2 - норма");
	messages["prd_control@123gv02_2"].setMessage("*:not", "norma", "125УУ04", "ПУМ 123ГВ02-2 - отключен");

	messages["prd_control_panel@123bb01_1"].setMessage("*:avar", "avar", "125УУ04", "123ББ01-1 - авария");
	messages["prd_control_panel@123bb01_1"].setMessage("avar:norma", "norma", "125УУ04", "123ББ01-1 - норма");
	messages["prd_control_panel@123bb01_2"].setMessage("*:avar", "avar", "125УУ04", "123ББ01-2 - авария");
	messages["prd_control_panel@123bb01_2"].setMessage("avar:norma", "norma", "125УУ04", "123ББ01-2 - норма");
	messages["prd_control_panel@123bb01_3"].setMessage("*:avar", "avar", "125УУ04", "123ББ01-3 - авария");
	messages["prd_control_panel@123bb01_3"].setMessage("avar:norma", "norma", "125УУ04", "123ББ01-3 - норма");
	messages["prd_control_panel@123bb01_4"].setMessage("*:avar", "avar", "125УУ04", "123ББ01-4 - авария");
	messages["prd_control_panel@123bb01_4"].setMessage("avar:norma", "norma", "125УУ04", "123ББ01-4 - норма");

	messages["prd_control@qf_vent_1"].setMessage("*:avar", "avar", "125УУ04", "Защ. Общ. Вент 1 - авария");
	messages["prd_control@qf_vent_1"].setMessage("avar:norma", "norma", "125УУ04", "Защ. Общ. Вент 1 - норма");
	messages["prd_control@qf_vent_2"].setMessage("*:avar", "avar", "125УУ04", "Защ. Общ. Вент 2 - авария");
	messages["prd_control@qf_vent_2"].setMessage("avar:norma", "norma", "125УУ04", "Защ. Общ. Вент 2 - норма");

	messages["prd_control@chp_1"].setMessage("*:avar", "avar", "125УУ04", "ЧП-1 - авария");
	messages["prd_control@chp_1"].setMessage("*:error", "error", "125УУ04", "ЧП-1 - неисправность");
	messages["prd_control@chp_1"].setMessage("avar,error:norma", "norma", "125УУ04", "ЧП-1 - норма");
	messages["prd_control@chp_2"].setMessage("*:avar", "avar", "125УУ04", "ЧП-2 - авария");
	messages["prd_control@chp_2"].setMessage("*:error", "error", "125УУ04", "ЧП-2 - неисправность");
	messages["prd_control@chp_2"].setMessage("avar,error:norma", "norma", "125УУ04", "ЧП-2 - норма");
	messages["prd_control@chp_3"].setMessage("*:avar", "avar", "125УУ04", "ЧП-3 - авария");
	messages["prd_control@chp_3"].setMessage("*:error", "error", "125УУ04", "ЧП-3 - неисправность");
	messages["prd_control@chp_3"].setMessage("avar,error:norma", "norma", "125УУ04", "ЧП-3 - норма");
	messages["prd_control@chp_4"].setMessage("*:avar", "avar", "125УУ04", "ЧП-4 - авария");
	messages["prd_control@chp_4"].setMessage("*:error", "error", "125УУ04", "ЧП-4 - неисправность");
	messages["prd_control@chp_4"].setMessage("avar,error:norma", "norma", "125УУ04", "ЧП-4 - норма");

	for(quint32 p = 0; p < 2; p++)
		for(quint32 m = 0; m < 32; m++)
		{
			QString N_MOD = QString("prd%1_base@umi%2").arg(p+1).arg(m+1);
			QString N_UMI = QString("УМИ-%1").arg(m+1);
			QString N_GG  = QString("126ГГ02-%1").arg(p+1);
			messages[N_MOD].setMessage("*:avar", "avar", N_GG, N_UMI + " - авария");
			messages[N_MOD].setMessage("avar:norma", "norma", N_GG, N_UMI + " - норма");
		}

	messages["aorls"].setMessage("*:avar", "avar", "АСКУ", "АО РЛС - сигнал установлен");
	messages["aorls"].setMessage("avar:norma", "norma", "АСКУ", "АО РЛС - сигнал cнят");
	messages["period"].setMessage("*:avar", "avar", "АСКУ", "Период вращения - не норма");
	messages["period"].setMessage("*:norma", "norma", "АСКУ", "Период вращения - норма");
	messages["124ee02@otkl_cont_380v"].setMessage("*:avar", "avar", "124ЭЭ02", "Контактор 380В - отключен");
	messages["124ee02@otkl_cont_380v"].setMessage("avar:norma", "norma", "124ЭЭ02", "Контактор 380В - включен");

	messages["124ee02@p27v_pit_signal"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ПИТАН СИГН - авария");
	messages["124ee02@p27v_pit_signal"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ПИТАН СИГН - норма");
	messages["124ee02@p27v_124yy03_1"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В 124УУ03-1 - авария");
	messages["124ee02@p27v_124yy03_1"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В 124УУ03-1 - норма");
	messages["124ee02@p27v_124yy03_2"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В 124УУ03-2 - авария");
	messages["124ee02@p27v_124yy03_2"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В 124УУ03-2 - норма");
	messages["124ee02@p27v_123bb02"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В 123ББ02 - авария");
	messages["124ee02@p27v_123bb02"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В 123ББ02 - норма");
	messages["124ee02@p27v_pit_avt"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ПИТ АВТ - авария");
	messages["124ee02@p27v_pit_avt"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ПИТ АВТ - норма");
	messages["124ee02@p27v_howl1"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В РЕВУН 1 - авария");
	messages["124ee02@p27v_howl1"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В РЕВУН 1 - норма");
	messages["124ee02@p27v_howl2"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В РЕВУН 2 - авария");
	messages["124ee02@p27v_howl2"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В РЕВУН 2 - норма");
	messages["124ee02@p27v_prm1"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ПРМ 1 - авария");
	messages["124ee02@p27v_prm1"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ПРМ 1 - норма");
	messages["124ee02@p27v_prm2"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ПРМ 2 - авария");
	messages["124ee02@p27v_prm2"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ПРМ 2 - норма");
	messages["124ee02@p27v_mspd"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В МСПД - авария");
	messages["124ee02@p27v_mspd"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В МСПД - норма");
	messages["124ee02@p27v_mspd"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В МСПД - авария");
	messages["124ee02@p27v_mspd"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В МСПД - норма");
	messages["124ee02@p27v_a15"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А15 - авария");
	messages["124ee02@p27v_a15"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А15 - норма");
	messages["124ee02@p27v_a16"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А16 - авария");
	messages["124ee02@p27v_a16"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А16 - норма");
	messages["124ee02@p27v_a17"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А17 - авария");
	messages["124ee02@p27v_a17"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А17 - норма");
	messages["124ee02@p27v_a18"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А18 - авария");
	messages["124ee02@p27v_a18"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А18 - норма");
	messages["124ee02@p27v_a19"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А19 - авария");
	messages["124ee02@p27v_a19"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А19 - норма");
	messages["124ee02@p27v_a20"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А20 - авария");
	messages["124ee02@p27v_a20"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А20 - норма");
	messages["124ee02@p27v_zu1"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ЗУ 1 - авария");
	messages["124ee02@p27v_zu1"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ЗУ 1 - норма");
	messages["124ee02@p27v_zu2"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ЗУ 2 - авария");
	messages["124ee02@p27v_zu2"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ЗУ 2 - норма");
	messages["124ee02@p27v_ps1"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ПС 1 - авария");
	messages["124ee02@p27v_ps1"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ПС 1 - норма");
	messages["124ee02@p27v_ps2"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ПС 2 - авария");
	messages["124ee02@p27v_ps2"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ПС 2 - норма");
	messages["124ee02@p27v_123gv02_1"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В 123ГВ02-1 - авария");
	messages["124ee02@p27v_123gv02_1"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В 123ГВ02-1 - норма");
	messages["124ee02@p27v_123gv02_2"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В 123ГВ02-2 - авария");
	messages["124ee02@p27v_123gv02_2"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В 123ГВ02-2 - норма");
	messages["124ee02@p27v_azs1"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В АЗИМ ДАТЧ 1 - авария");
	messages["124ee02@p27v_azs1"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В АЗИМ ДАТЧ 1 - норма");
	messages["124ee02@p27v_azs2"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В АЗИМ ДАТЧ 2 - авария");
	messages["124ee02@p27v_azs2"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В АЗИМ ДАТЧ 2 - норма");
	messages["124ee02@p27v_gsh"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ГШ - авария");
	messages["124ee02@p27v_gsh"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ГШ - норма");
	messages["124ee02@p27v_opu"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В ОПУ - авария");
	messages["124ee02@p27v_opu"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В ОПУ - норма");
	messages["124ee02@p27v_a31"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А31 - авария");
	messages["124ee02@p27v_a31"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А31 - норма");
	messages["124ee02@p27v_a32"].setMessage("*:avar", "avar", "124ЭЭ02", "Предохранитель 27В А32 - авария");
	messages["124ee02@p27v_a32"].setMessage("avar:norma", "norma", "124ЭЭ02", "Предохранитель 27В А32 - норма");
	messages["124ee02@qf_accum"].setMessage("*:avar", "avar", "124ЭЭ02", "QF АККУМ - отключен");
	messages["124ee02@qf_accum"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF АККУМ - включен");
	messages["124ee02@qf_124yy08"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 124УУ08 - отключен");
	messages["124ee02@qf_124yy08"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 124УУ08 - включен");
	messages["124ee02@qf_124yg02"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 124УГ02 - отключен");
	messages["124ee02@qf_124yg02"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 124УГ02 - включен");
	messages["124ee02@qf_27v_buf"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 27В БУФ - отключен");
	messages["124ee02@qf_27v_buf"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 27В БУФ - включен");
	messages["124ee02@qf_pos"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ПОС - отключен");
	messages["124ee02@qf_pos"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ПОС - включен");
	messages["124ee02@qf_prm1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ПРМ 1 - отключен");
	messages["124ee02@qf_prm1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ПРМ 1 - включен");
	messages["124ee02@qf_prm2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ПРМ 2 - отключен");
	messages["124ee02@qf_prm2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ПРМ 2 - включен");
	messages["124ee02@qf_trm"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ТРМ - отключен");
	messages["124ee02@qf_trm"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ТРМ - включен");
	messages["124ee02@qf_27v_c"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 27В Ц - отключен");
	messages["124ee02@qf_27v_c"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 27В Ц - включен");
	messages["124ee02@qf_avar_osv"].setMessage("*:avar", "avar", "124ЭЭ02", "QF АВАР ОСВ - отключен");
	messages["124ee02@qf_avar_osv"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF АВАР ОСВ - включен");
	messages["124ee02@qf_380v_set"].setMessage("*:avar", "avar", "124ЭЭ02", "QF СЕТЬ 380В - отключен");
	messages["124ee02@qf_380v_set"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF СЕТЬ 380В - включен");
	messages["124ee02@qf_osv_apm"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ОСВ АПМ - отключен");
	messages["124ee02@qf_osv_apm"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ОСВ АПМ - включен");
	messages["124ee02@qf_osv_perim"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ОСВ ПЕРИМ - отключен");
	messages["124ee02@qf_osv_perim"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ОСВ ПЕРИМ - включен");
	messages["124ee02@qf_380v_rpu"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 380В РПУ - отключен");
	messages["124ee02@qf_380v_rpu"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 380В РПУ - включен");
	messages["124ee02@qf_teplovent"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ТЕПЛОВЕНТ - отключен");
	messages["124ee02@qf_teplovent"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ТЕПЛОВЕНТ - включен");
	messages["124ee02@qf_sotr"].setMessage("*:avar", "avar", "124ЭЭ02", "QF СОТР - отключен");
	messages["124ee02@qf_sotr"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF СОТР - включен");
	messages["124ee02@qf_rozet_220v"].setMessage("*:avar", "avar", "124ЭЭ02", "QF РОЗЕТ 220В - отключен");
	messages["124ee02@qf_rozet_220v"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF РОЗЕТ 220В - включен");
	messages["124ee02@qf_ups1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ИБП 1 - отключен");
	messages["124ee02@qf_ups1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ИБП 1 - включен");
	messages["124ee02@qf_ups2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ИБП 2 - отключен");
	messages["124ee02@qf_ups2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ИБП 2 - включен");
	messages["124ee02@qf_prd1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ПРД 1 - отключен");
	messages["124ee02@qf_prd1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ПРД 1 - включен");
	messages["124ee02@qf_prd2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF ПРД 2 - отключен");
	messages["124ee02@qf_prd2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF ПРД 2 - включен");
	messages["124ee02@qf_124yy03_1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 124УУ03-1 - отключен");
	messages["124ee02@qf_124yy03_1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 124УУ03-1 - включен");
	messages["124ee02@qf_124yy03_2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 124УУ03-2 - отключен");
	messages["124ee02@qf_124yy03_2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 124УУ03-2 - включен");
	messages["124ee02@qf_kmvrl1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF МВРЛ 1 - отключен");
	messages["124ee02@qf_kmvrl1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF МВРЛ 1 - включен");
	messages["124ee02@qf_kmvrl2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF МВРЛ 2 - отключен");
	messages["124ee02@qf_kmvrl2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF МВРЛ 2 - включен");
	messages["124ee02@qf_obr1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF АПП ОБР 1 - отключен");
	messages["124ee02@qf_obr1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF АПП ОБР 1 - включен");
	messages["124ee02@qf_obr2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF АПП ОБР 2 - отключен");
	messages["124ee02@qf_obr2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF АПП ОБР 2 - включен");
	messages["124ee02@qf_cond1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF КОНДИЦ 1 - отключен");
	messages["124ee02@qf_cond1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF КОНДИЦ 1 - включен");
	messages["124ee02@qf_cond2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF КОНДИЦ 2 - отключен");
	messages["124ee02@qf_cond2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF КОНДИЦ 2 - включен");
	messages["124ee02@qf_123bb01_1"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 123ББ01-1 - отключен");
	messages["124ee02@qf_123bb01_1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-1 - включен");
	messages["124ee02@qf_123bb01_2"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 123ББ01-2 - отключен");
	messages["124ee02@qf_123bb01_2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-2 - включен");
	messages["124ee02@qf_123bb01_3"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 123ББ01-3 - отключен");
	messages["124ee02@qf_123bb01_3"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-3 - включен");
	messages["124ee02@qf_123bb01_4"].setMessage("*:avar", "avar", "124ЭЭ02", "QF 123ББ01-4 - отключен");
	messages["124ee02@qf_123bb01_4"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-4 - включен");
	messages["124ee02@123bb01_1"].setMessage("*:avar", "avar", "124ЭЭ02", "123ББ01-1 - авария");
	messages["124ee02@123bb01_1"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-1 - норма");
	messages["124ee02@123bb01_2"].setMessage("*:avar", "avar", "124ЭЭ02", "123ББ01-2 - авария");
	messages["124ee02@123bb01_2"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-2 - норма");
	messages["124ee02@123bb01_3"].setMessage("*:avar", "avar", "124ЭЭ02", "123ББ01-3 - авария");
	messages["124ee02@123bb01_3"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-3 - норма");
	messages["124ee02@123bb01_4"].setMessage("*:avar", "avar", "124ЭЭ02", "123ББ01-4 - авария");
	messages["124ee02@123bb01_4"].setMessage("avar:norma", "norma", "124ЭЭ02", "QF 123ББ01-4 - норма");
	messages["125yy03@put_reset_avar"].setMessage("*:avar", "avar", "АСКУ", "НАЖАТЬ СБРОС АВАРИИ ОБЩ - сигнал установлен");
	messages["125yy03@put_reset_avar"].setMessage("avar:norma", "norma", "АСКУ", "НАЖАТЬ СБРОС АВАРИИ ОБЩ - сигнал cнят");

	messages["125yy03@vkl_cont_osv_perim"].setMessage("norma:avar", "avar", "125УУ03", "Контактор ОСВ ПЕРИМ - отключен");
	messages["125yy03@vkl_cont_osv_perim"].setMessage("avar:norma", "norma", "125УУ03", "Контактор ОСВ ПЕРИМ - включен");
//	messages["125yy03@vkl_cont_osv_rpu"].setMessage("norma:avar", "avar", "125УУ03", "Контактор ОСВ РПУ - отключен");
//	messages["125yy03@vkl_cont_osv_rpu"].setMessage("avar:norma", "norma", "125УУ03", "Контактор ОСВ РПУ - включен");
	messages["125yy03@vent1"].setMessage("*:avar", "avar", "125УУ03", "Вентилятор 1 - авария");
	messages["125yy03@vent1"].setMessage("avar:norma", "norma", "125УУ03", "Вентилятор 1 - норма");
	messages["125yy03@vent2"].setMessage("*:avar", "avar", "125УУ03", "Вентилятор 2 - авария");
	messages["125yy03@vent2"].setMessage("avar:norma", "norma", "125УУ03", "Вентилятор 2 - норма");
	messages["125yy03@123bb02"].setMessage("*:avar", "avar", "125УУ03", "123ББ02 - авария");
	messages["125yy03@123bb02"].setMessage("avar:norma", "norma", "125УУ03", "123ББ02 - норма");
	messages["125yy03@sensor_p"].setMessage("*:avar", "avar", "125УУ03", "Датчик давления - авария");
	messages["125yy03@sensor_p"].setMessage("avar:norma", "norma", "125УУ03", "Датчик давления - норма");
	messages["125yy03@sensor_t1"].setMessage("*:avar", "avar", "125УУ03", "Датчик температуры 1 - авария");
	messages["125yy03@sensor_t1"].setMessage("avar:norma", "norma", "125УУ03", "Датчик температуры 1 - норма");
	messages["125yy03@sensor_t2"].setMessage("*:avar", "avar", "125УУ03", "Датчик температуры 2 - авария");
	messages["125yy03@sensor_t2"].setMessage("avar:norma", "norma", "125УУ03", "Датчик температуры 2 - норма");
	messages["125yy03@sensor_t3"].setMessage("*:avar", "avar", "125УУ03", "Датчик температуры 3 - авария");
	messages["125yy03@sensor_t3"].setMessage("avar:norma", "norma", "125УУ03", "Датчик температуры 3 - норма");
	messages["125yy03@accum_24v"].setMessage("*:avar", "avar", "125УУ03", "24В АККУМ - авария");
	messages["125yy03@accum_24v"].setMessage("avar:norma", "norma", "125УУ03", "24В АККУМ - норма");
	messages["125yy03@ups1_error"].setMessage("*:avar", "avar", "125УУ03", "Неисправность ИБП 1 - сигнал установлен");
	messages["125yy03@ups1_error"].setMessage("avar:norma", "norma", "125УУ03", "Неисправность ИБП 1 - сигнал снят");
	messages["125yy03@ups2_error"].setMessage("*:avar", "avar", "125УУ03", "Неисправность ИБП 2 - сигнал установлен");
	messages["125yy03@ups2_error"].setMessage("avar:norma", "norma", "125УУ03", "Неисправность ИБП 2 - сигнал снят");
	messages["125yy03@block_opu"].setMessage("*:avar", "avar", "125УУ03", "БЛОКИРОВКА ОПУ НАРУШЕНА - сигнал установлен");
	messages["125yy03@block_opu"].setMessage("avar:norma", "norma", "125УУ03", "БЛОКТРОВКА ОПУ НАРУШЕНА - сигнал снят");
	messages["125yy03@opu_open"].setMessage("*:avar", "avar", "125УУ03", "ЛЮК ОПУ ОТКРЫТ - сигнал установлен");
	messages["125yy03@opu_open"].setMessage("avar:norma", "norma", "125УУ03", "ЛЮК ОПУ ОТКРЫТ - сигнал снят");
	messages["125yy03@work_cond_1"].setMessage("norma:avar", "simple", "125УУ03", "РАБОТА КОНДИЦИОНЕРА 1 - сигнал снят");
	messages["125yy03@work_cond_1"].setMessage("avar:norma", "simple", "125УУ03", "РАБОТА КОНДИЦИОНЕРА 1 - сигнал установлен");
	messages["125yy03@work_cond_2"].setMessage("norma:avar", "simple", "125УУ03", "РАБОТА КОНДИЦИОНЕРА 2 - сигнал снят");
	messages["125yy03@work_cond_2"].setMessage("avar:norma", "simple", "125УУ03", "РАБОТА КОНДИЦИОНЕРА 2 - сигнал установлен");
	messages["125yy03@avar124yg02"].setMessage("*:avar", "avar", "125УУ03", "124УГ02 - авария");
	messages["125yy03@avar124yg02"].setMessage("avar:norma", "norma", "125УУ03", "124УГ02 - норма");

	messages["sotr@cond1_controller"].setMessage("*:avar", "avar", "СОТР", "Контроллер кондиционера 1 - авария");
	messages["sotr@cond1_controller"].setMessage("avar:norma", "norma", "СОТР", "Контроллер кондиционера 1 - норма");
	messages["sotr@cond2_controller"].setMessage("*:avar", "avar", "СОТР", "Контроллер кондиционера 2 - авария");
	messages["sotr@cond2_controller"].setMessage("avar:norma", "norma", "СОТР", "Контроллер кондиционера 2 - норма");
	messages["sotr@cond1_sensor1"].setMessage("*:avar", "avar", "Кондиционер 1", "Датчик U1 - авария");
	messages["sotr@cond1_sensor1"].setMessage("avar:norma", "norma", "Кондиционер 1", "Датчик U1 - норма");
	messages["sotr@cond1_sensor2"].setMessage("*:avar", "avar", "Кондиционер 1", "Датчик U2 - авария");
	messages["sotr@cond1_sensor2"].setMessage("avar:norma", "norma", "Кондиционер 1", "Датчик U2 - норма");
	messages["sotr@cond2_sensor1"].setMessage("*:avar", "avar", "Кондиционер 2", " Датчик U1 - авария");
	messages["sotr@cond2_sensor1"].setMessage("avar:norma", "norma", "Кондиционер 2", "Датчик U1 - норма");
	messages["sotr@cond2_sensor2"].setMessage("*:avar", "avar", "Кондиционер 2", "Датчик U2 - авария");
	messages["sotr@cond2_sensor2"].setMessage("avar:norma", "norma", "Кондиционер 2", "Датчик U2 - норма");
	messages["sotr@cond1_compressor"].setMessage("*:avar", "avar", "Кондиционер 1", "Компрессор - авария");
	messages["sotr@cond1_compressor"].setMessage("avar:norma", "norma", "Кондиционер 1", "Компрессор - норма");
	messages["sotr@cond2_compressor"].setMessage("*:avar", "avar", "Кондиционер 2", "Компрессор - авария");
	messages["sotr@cond2_compressor"].setMessage("avar:norma", "norma", "Кондиционер 2", "Компрессор - норма");
	messages["sotr@cond1_vent_recycle"].setMessage("*:avar", "avar", "Кондиционер 1", "Вентилятор рециркуляции - авария");
	messages["sotr@cond1_vent_recycle"].setMessage("avar:norma", "norma", "Кондиционер 1", "Вентилятор рециркуляции - норма");
	messages["sotr@cond2_vent_recycle"].setMessage("*:avar", "avar", "Кондиционер 2", "Вентилятор рециркуляции - авария");
	messages["sotr@cond2_vent_recycle"].setMessage("avar:norma", "norma", "Кондиционер 2", "Вентилятор рециркуляции - норма");
	messages["sotr@cond1_vent_condensor"].setMessage("*:avar", "avar", "Кондиционер 1", "Вентилятор конденсора - авария");
	messages["sotr@cond1_vent_condensor"].setMessage("avar:norma", "norma", "Кондиционер 1", "Вентилятор конденсора - норма");
	messages["sotr@cond2_vent_condensor"].setMessage("*:avar", "avar", "Кондиционер 2", "Вентилятор конденсора - авария");
	messages["sotr@cond2_vent_condensor"].setMessage("avar:norma", "norma", "Кондиционер 2", "Вентилятор конденсора - норма");
	messages["sotr@cond1_pressure_high"].setMessage("*:avar", "avar", "Кондиционер 1", "Высокое давление - сигнал установлен");
	messages["sotr@cond1_pressure_high"].setMessage("avar:norma", "norma", "Кондиционер 1", "Высокое давление - сигнал снят");
	messages["sotr@cond2_pressure_high"].setMessage("*:avar", "avar", "Кондиционер 2", "Высокое давление - сигнал установлен");
	messages["sotr@cond2_pressure_high"].setMessage("avar:norma", "norma", "Кондиционер 2", "Высокое давление - сигнал снят");
	messages["sotr@cond1_pressure_low"].setMessage("*:avar", "avar", "Кондиционер 1", "Низкое давление - сигнал установлен");
	messages["sotr@cond1_pressure_low"].setMessage("avar:norma", "norma", "Кондиционер 1", "Низкое давление - сигнал снят");
	messages["sotr@cond2_pressure_low"].setMessage("*:avar", "avar", "Кондиционер 2", "Низкое давление - сигнал установлен");
	messages["sotr@cond2_pressure_low"].setMessage("avar:norma", "norma", "Кондиционер 2", "Низкое давление - сигнал снят");

	messages["sotr@123ya03_1"].setMessage("*:avar", "avar", "СОТР", "123УА03-1 - авария");
	messages["sotr@123ya03_1"].setMessage("*:error", "error", "СОТР", "123УА03-1 - неисправность");
	messages["sotr@123ya03_1"].setMessage("avar,error:norma", "norma", "СОТР", "123УА03-1 - норма");
	messages["sotr@123ya03_2"].setMessage("*:avar", "avar", "СОТР", "123УА03-2 - авария");
	messages["sotr@123ya03_2"].setMessage("*:error", "error", "СОТР", "123УА03-2 - неисправность");
	messages["sotr@123ya03_2"].setMessage("avar,error:norma", "norma", "СОТР", "123УА03-2 - норма");
	messages["sotr@123ya03_3"].setMessage("*:avar", "avar", "СОТР", "123УА03-3 - авария");
	messages["sotr@123ya03_3"].setMessage("*:error", "error", "СОТР", "123УА03-3 - неисправность");
	messages["sotr@123ya03_3"].setMessage("avar,error:norma", "norma", "СОТР", "123УА03-3 - норма");
	messages["sotr@123ya03_4"].setMessage("*:avar", "avar", "СОТР", "123УА03-4 - авария");
	messages["sotr@123ya03_4"].setMessage("*:error", "error", "СОТР", "123УА03-4 - неисправность");
	messages["sotr@123ya03_4"].setMessage("avar,error:norma", "norma", "СОТР", "123УА03-4 - норма");
	messages["sotr@zasl1"].setMessage("*:avar", "avar", "123УА03-1", "Заслонка 1 - авария");
	messages["sotr@zasl1"].setMessage("avar:norma", "norma", "123УА03-1", "Заслонка 1 - норма");
	messages["sotr@zasl2"].setMessage("*:avar", "avar", "123УА03-2", "Заслонка 2 - авария");
	messages["sotr@zasl2"].setMessage("avar:norma", "norma", "123УА03-2", "Заслонка 2 - норма");
	messages["sotr@zasl3"].setMessage("*:avar", "avar", "123УА03-3", "Заслонка 3 - авария");
	messages["sotr@zasl3"].setMessage("avar:norma", "norma", "123УА03-3", "Заслонка 3 - норма");
	messages["sotr@zasl4"].setMessage("*:avar", "avar", "123УА03-4", "Заслонка 4 - авария");
	messages["sotr@zasl4"].setMessage("avar:norma", "norma", "123УА03-4", "Заслонка 4 - норма");
	messages["sotr@zasl1_opened"].setMessage("*:norma", "simple", "123УА03-1", "Заслонка 1 - открыта");
	messages["sotr@zasl2_opened"].setMessage("*:norma", "simple", "123УА03-2", "Заслонка 2 - открыта");
	messages["sotr@zasl3_opened"].setMessage("*:norma", "simple", "123УА03-3", "Заслонка 3 - открыта");
	messages["sotr@zasl4_opened"].setMessage("*:norma", "simple", "123УА03-4", "Заслонка 4 - открыта");
	messages["sotr@zasl1_closed"].setMessage("*:norma", "simple", "123УА03-1", "Заслонка 1 - закрыта");
	messages["sotr@zasl2_closed"].setMessage("*:norma", "simple", "123УА03-2", "Заслонка 2 - закрыта");
	messages["sotr@zasl3_closed"].setMessage("*:norma", "simple", "123УА03-3", "Заслонка 3 - закрыта");
	messages["sotr@zasl4_closed"].setMessage("*:norma", "simple", "123УА03-4", "Заслонка 4 - закрыта");
	messages["sotr@vent1"].setMessage("*:avar", "avar", "123УА03-1", "Вентилятор 1 - авария");
	messages["sotr@vent1"].setMessage("avar:norma", "norma", "123УА03-1", "Вентилятор 1 - норма");
	messages["sotr@vent2"].setMessage("*:avar", "avar", "123УА03-2", "Вентилятор 2 - авария");
	messages["sotr@vent2"].setMessage("avar:norma", "norma", "123УА03-2", "Вентилятор 2 - норма");
	messages["sotr@t_internal"].setMessage("*:avar", "avar", "СОТР", "Внутренняя температура - вне допустимых пределов");
	messages["sotr@t_internal"].setMessage("*:error", "error", "СОТР", "Внутренняя температура - близка к допустимым пределам");
	messages["sotr@t_internal"].setMessage("avar,error:norma", "norma", "СОТР", "Внутренняя температура - в пределах нормы");

	messages["prm@124vp02_1"].setMessage("*:avar", "avar", "ПРМ", "124ВП02-1 - авария");
	messages["prm@124vp02_1"].setMessage("avar:norma", "norma", "ПРМ", "124ВП02-1 - норма");
	messages["prm@124vp02_2"].setMessage("*:avar", "avar", "ПРМ", "124ВП02-2 - авария");
	messages["prm@124vp02_2"].setMessage("avar:norma", "norma", "ПРМ", "124ВП02-2 - норма");
	messages["prm@d2ht502_1"].setMessage("*:avar", "avar", "ПРМ", "Д2ХТ502-1 - авария");
	messages["prm@d2ht502_1"].setMessage("avar:norma", "norma", "ПРМ", "Д2ХТ502-1 - норма");
	messages["prm@d2ht502_2"].setMessage("*:avar", "avar", "ПРМ", "Д2ХТ502-2 - авария");
	messages["prm@d2ht502_2"].setMessage("avar:norma", "norma", "ПРМ", "Д2ХТ502-2 - норма");
	messages["prm@d2en429"].setMessage("*:avar", "avar", "124ПП04", "Д2ЕН429 - авария");
	messages["prm@d2en429"].setMessage("avar:norma", "norma", "124ПП04", "Д2ЕН429 - норма");
	messages["prm@switch_s"].setMessage("*:avar", "avar", "124ПП04", "СВЧ коммутатор суммарный - авария");
	messages["prm@switch_s"].setMessage("avar:norma", "norma", "124ПП04", "СВЧ коммутатор суммарный - норма");
	messages["prm@switch_d"].setMessage("*:avar", "avar", "124ПП04", "СВЧ коммутатор разностный - авария");
	messages["prm@switch_d"].setMessage("avar:norma", "norma", "124ПП04", "СВЧ коммутатор разностный - норма");
	messages["prm@124pp03_1"].setMessage("*:avar", "avar", "124ПП04", "123ПП03-1 - авария");
	messages["prm@124pp03_1"].setMessage("avar:norma", "norma", "124ПП04", "123ПП03-1 - норма");
	messages["prm@124pp03_2"].setMessage("*:avar", "avar", "124ПП04", "123ПП03-2 - авария");
	messages["prm@124pp03_2"].setMessage("avar:norma", "norma", "124ПП04", "123ПП03-2 - норма");

	messages["126pk01@Communicator1"].setMessage("*:avar", "avar", "126ПК01", "Коммуникатор 1 - авария");
	messages["126pk01@Communicator1"].setMessage("*:error", "error", "126ПК01", "Коммуникатор 1 - неисправность");
	messages["126pk01@Communicator1"].setMessage("avar,error:norma", "norma", "126ПК01", "Коммуникатор 1 - норма");
	messages["126pk01@Communicator2"].setMessage("*:avar", "avar", "126ПК01", "Коммуникатор 2 - авария");
	messages["126pk01@Communicator2"].setMessage("*:error", "error", "126ПК01", "Коммуникатор 2 - неисправность");
	messages["126pk01@Communicator2"].setMessage("avar:norma", "norma", "126ПК01", "Коммуникатор 2 - норма");

	messages["svkr1@123gf01"].setMessage("*:avar", "avar", "СВ КР-4 - 1", "123ГФ01 - авария");
	messages["svkr1@123gf01"].setMessage("avar:norma", "norma", "СВ КР-4 - 1", "123ГФ01 - норма");
	messages["svkr1@dasd"].setMessage("*:avar", "avar", "СВ КР-4 - 1", "Д2ВК028 - авария");
	messages["svkr1@dasd"].setMessage("avar:norma", "norma", "СВ КР-4 - 1", "Д2ВК028 - норма");
	messages["svkr2@123gf01"].setMessage("*:avar", "avar", "СВ КР-4 - 2", "123ГФ01 - авария");
	messages["svkr2@123gf01"].setMessage("avar:norma", "norma", "СВ КР-4 - 2", "123ГФ01 - норма");
	messages["svkr2@dasd"].setMessage("*:avar", "avar", "СВ КР-4 - 2", "Д2ВК028 - авария");
	messages["svkr2@dasd"].setMessage("avar:norma", "norma", "СВ КР-4 - 2", "Д2ВК028 - норма");

	messages["ant@sensor1"].setMessage("*:avar", "avar", "Ант.модуль", "Азимутальный датчик 1 - авария");
	messages["ant@sensor1"].setMessage("avar:norma", "norma", "Ант.модуль", "Азимутальный датчик 1 - норма");
	messages["ant@sensor2"].setMessage("*:avar", "avar", "Ант.модуль", "Азимутальный датчик 2 - авария");
	messages["ant@sensor2"].setMessage("avar:norma", "norma", "Ант.модуль", "Азимутальный датчик 2 - норма");

	messages["drive1@mest"].setMessage("*:mest", "switch", "124УУ03-1", "Режим работы - местное управление");
	messages["drive1@mest"].setMessage("mest:norma", "switch", "124УУ03-1", "Режим работы - дистанционное управление");
	messages["drive2@mest"].setMessage("*:mest", "switch", "124УУ03-2", "Режим работы - местное управление");
	messages["drive2@mest"].setMessage("mest:norma", "switch", "124УУ03-2", "Режим работы - дистанционное управление");
	messages["drive1@ready"].setMessage("*:avar", "avar", "124УУ03-1", "Нет готовности");
	messages["drive1@ready"].setMessage("avar:norma", "norma", "124УУ03-1", "Готовность - сигнал установлен");
	messages["drive2@ready"].setMessage("*:avar", "avar", "124УУ03-2", "Нет готовности");
	messages["drive2@ready"].setMessage("avar:norma", "norma", "124УУ03-2", "Готовность - сигнал установлен");
	messages["drive1@warning"].setMessage("*:avar", "error", "124УУ03-1", "Внимание");
	messages["drive1@warning"].setMessage("avar:norma", "norma", "124УУ03-1", "Внимание - сигнал снят");
	messages["drive2@warning"].setMessage("*:avar", "error", "124УУ03-2", "Внимание");
	messages["drive2@warning"].setMessage("avar:norma", "norma", "124УУ03-2", "Внимание - сигнал снят");
	messages["drive1@fail"].setMessage("*:avar", "avar", "124УУ03-1", "Авария");
	messages["drive1@fail"].setMessage("avar:norma", "norma", "124УУ03-1", "Авария - сигнал снят");
	messages["drive2@fail"].setMessage("*:avar", "avar", "124УУ03-2", "Авария");
	messages["drive2@fail"].setMessage("avar:norma", "norma", "124УУ03-2", "Авария - сигнал снят");
	messages["drive1@working"].setMessage("*:norma", "norma", "124УУ03-1", "Работа");
	messages["drive1@working"].setMessage("norma:*", "norma", "124УУ03-1", "Работа - сигнал снят");
	messages["drive2@working"].setMessage("*:norma", "norma", "124УУ03-2", "Работа");
	messages["drive2@working"].setMessage("norma:*", "norma", "124УУ03-2", "Работа - сигнал снят");
	messages["drive1@invertor"].setMessage("*:avar", "avar", "124УУ03-1", "Авария инвертора");
	messages["drive1@invertor"].setMessage("avar:norma", "norma", "124УУ03-1", "Авария инвертора - сигнал снят");
	messages["drive2@invertor"].setMessage("*:avar", "avar", "124УУ03-2", "Авария инвертора");
	messages["drive2@invertor"].setMessage("avar:norma", "norma", "124УУ03-2", "Авария инвертора - сигнал снят");
	messages["drive1@power"].setMessage("*:avar", "avar", "124УУ03-1", "Силовой блок не готов");
	messages["drive1@power"].setMessage("avar:norma", "norma", "124УУ03-1", "Силовой блок готов");
	messages["drive2@power"].setMessage("*:avar", "avar", "124УУ03-2", "Силовой блок не готов");
	messages["drive2@power"].setMessage("avar:norma", "norma", "124УУ03-2", "Силовой блок готов");
	messages["drive1@sensor"].setMessage("*:avar", "avar", "124УУ03-1", "Авария датчика");
	messages["drive1@sensor"].setMessage("avar:norma", "norma", "124УУ03-1", "Авария датчика - сигнал снят");
	messages["drive2@sensor"].setMessage("*:avar", "avar", "124УУ03-2", "Авария датчика");
	messages["drive2@sensor"].setMessage("avar:norma", "norma", "124УУ03-2", "Авария датчика - сигнал снят");

	messages["ups1@ups_off"].setMessage("*:avar", "avar", "ИБП-1", "Режим работы - отключён");
	messages["ups1@bypass"].setMessage("*:avar", "error", "ИБП-1", "Режим работы - байпас");
	messages["ups1@on_battery"].setMessage("*:avar", "error", "ИБП-1", "Режим работы - на батареях");
	messages["ups1@ups_normal"].setMessage("*:avar", "norma", "ИБП-1", "Режим работы - норма");

	messages["ups2@ups_off"].setMessage("*:avar", "avar", "ИБП-2", "Режим работы - отключён");
	messages["ups2@bypass"].setMessage("*:avar", "error", "ИБП-2", "Режим работы - байпас");
	messages["ups2@on_battery"].setMessage("*:avar", "error", "ИБП-2", "Режим работы - на батареях");
	messages["ups2@ups_normal"].setMessage("*:avar", "norma", "ИБП-2", "Режим работы - норма");

	messages["voi1@data_prl"].setMessage("*:avar", "avar", "ВОИ-1", "Данные ПРЛ - авария");
	messages["voi1@data_prl"].setMessage("*:norma", "norma", "ВОИ-1", "Данные ПРЛ - норма");
	messages["voi2@data_prl"].setMessage("*:avar", "avar", "ВОИ-2", "Данные ПРЛ - авария");
	messages["voi2@data_prl"].setMessage("*:norma", "norma", "ВОИ-2", "Данные ПРЛ - норма");
	messages["voi1@data_vrl"].setMessage("*:avar", "avar", "ВОИ-1", "Данные ВРЛ - авария");
	messages["voi1@data_vrl"].setMessage("*:norma", "norma", "ВОИ-1", "Данные ВРЛ - норма");
	messages["voi2@data_vrl"].setMessage("*:avar", "avar", "ВОИ-2", "Данные ВРЛ - авария");
	messages["voi2@data_vrl"].setMessage("*:norma", "norma", "ВОИ-2", "Данные ВРЛ - норма");
	messages["voi1@data_nrz"].setMessage("*:avar", "avar", "ВОИ-1", "Данные НРЗ - авария");
	messages["voi1@data_nrz"].setMessage("*:norma", "norma", "ВОИ-1", "Данные НРЗ - норма");
	messages["voi2@data_nrz"].setMessage("*:avar", "avar", "ВОИ-2", "Данные НРЗ - авария");
	messages["voi2@data_nrz"].setMessage("*:norma", "norma", "ВОИ-2", "Данные НРЗ - норма");
	messages["voi1@data_azn"].setMessage("*:avar", "avar", "ВОИ-1", "Данные АЗН - авария");
	messages["voi1@data_azn"].setMessage("*:norma", "norma", "ВОИ-1", "Данные АЗН - норма");
	messages["voi2@data_azn"].setMessage("*:avar", "avar", "ВОИ-2", "Данные АЗН - авария");
	messages["voi2@data_azn"].setMessage("*:norma", "norma", "ВОИ-2", "Данные АЗН - норма");
	messages["voi1@data_mpsn"].setMessage("*:avar", "avar", "ВОИ-1", "Данные МПСН - авария");
	messages["voi1@data_mpsn"].setMessage("*:norma", "norma", "ВОИ-1", "Данные МПСН - норма");
	messages["voi2@data_mpsn"].setMessage("*:avar", "avar", "ВОИ-2", "Данные МПСН - авария");
	messages["voi2@data_mpsn"].setMessage("*:norma", "norma", "ВОИ-2", "Данные МПСН - норма");
	messages["voi1@driver"].setMessage("*:avar", "avar", "ВОИ-1", "Драйвер модуля Д2ВК028 - авария");
	messages["voi1@driver"].setMessage("avar:norma", "norma", "ВОИ-1", "Драйвер модуля Д2ВК028 - норма");
	messages["voi2@driver"].setMessage("*:avar", "avar", "ВОИ-2", "Драйвер модуля Д2ВК028 - авария");
	messages["voi2@driver"].setMessage("avar:norma", "norma", "ВОИ-2", "Драйвер модуля Д2ВК028 - норма");
	messages["voi1@failure"].setMessage("*:avar", "avar", "ВОИ-1", "Модуль Д2ВК028 - авария");
	messages["voi1@failure"].setMessage("avar:norma", "norma", "ВОИ-1", "Модуль Д2ВК028 - норма");
	messages["voi2@failure"].setMessage("*:avar", "avar", "ВОИ-2", "Модуль Д2ВК028 - авария");
	messages["voi2@failure"].setMessage("avar:norma", "norma", "ВОИ-2", "Модуль Д2ВК028 - норма");
	messages["voi1@invalid_time"].setMessage("*:avar", "error", "ВОИ-1", "Время не достоверно - авария");
	messages["voi1@invalid_time"].setMessage("avar:norma", "norma", "ВОИ-1", "Время достоверно - норма");
	messages["voi2@invalid_time"].setMessage("*:avar", "error", "ВОИ-2", "Время не достоверно - авария");
	messages["voi2@invalid_time"].setMessage("avar:norma", "norma", "ВОИ-2", "Время достоверно - норма");
	messages["voi1@disable"].setMessage("*:avar", "avar", "ВОИ-1", "Запрет излучения - установлен");
	messages["voi1@disable"].setMessage("avar:norma", "norma", "ВОИ-1", "Запрет излучения - снят");
	messages["voi2@disable"].setMessage("*:avar", "error", "ВОИ-2", "Запрет излучения - установлен");
	messages["voi2@disable"].setMessage("avar:norma", "norma", "ВОИ-2", "Запрет излучения - снят");
	messages["voi1@nord"].setMessage("*:avar", "avar", "ВОИ-1", "Отсутствует сигнал СЕВЕР - авария");
	messages["voi1@nord"].setMessage("avar:norma", "norma", "ВОИ-1", "Сигнал СЕВЕР - норма");
	messages["voi2@nord"].setMessage("*:avar", "avar", "ВОИ-2", "Отсутствует сигнал СЕВЕР - авария");
	messages["voi2@nord"].setMessage("avar:norma", "norma", "ВОИ-2", "Сигнал СЕВЕР - норма");
	messages["voi1@mai"].setMessage("*:avar", "avar", "ВОИ-1", "Отсутствует сигнал МАИ - авария");
	messages["voi1@mai"].setMessage("avar:norma", "norma", "ВОИ-1", "Сигналы МАИ - норма");
	messages["voi2@mai"].setMessage("*:avar", "avar", "ВОИ-2", "Отсутствуют сигналы МАИ - авария");
	messages["voi2@mai"].setMessage("avar:norma", "norma", "ВОИ-2", "Сигналы МАИ - норма");
	messages["voi1@sost"].setMessage("*:avar", "avar", "ВОИ-1", "Общее состояние ВОИ - авария");
	messages["voi1@sost"].setMessage("*:error", "error", "ВОИ-1", "Общее состояние ВОИ - неисправность");
	messages["voi1@sost"].setMessage("avar,error:norma", "norma", "ВОИ-1", "Общее состояние ВОИ - норма");
	messages["voi2@sost"].setMessage("*:avar", "avar", "ВОИ-2", "Общее состояние ВОИ - авария");
	messages["voi2@sost"].setMessage("*:error", "error", "ВОИ-2", "Общее состояние ВОИ - неисправность");
	messages["voi2@sost"].setMessage("avar,error:norma", "norma", "ВОИ-2", "Общее состояние ВОИ - норма");

	messages["prdsys@powermeter"].setMessage("*:not", "simple", "ИМ", "Мощность ПРД - отключена");
	messages["prdsys@powermeter"].setMessage("*:avar", "avar", "ИМ", "Мощность ПРД - вне допустимых пределов");
	messages["prdsys@powermeter"].setMessage("*:error", "error", "ИМ", "Мощность ПРД - близка к допустимым пределам");
	messages["prdsys@powermeter"].setMessage("*:norma", "norma", "ИМ", "Мощность ПРД - в пределах нормы");

	messages["prl@obSost"].setMessage("*:not", "not", "АСКУ", "Общее состояние ПОРЛ - отключен");
	messages["prl@obSost"].setMessage("*:avar", "avar", "АСКУ", "Общее состояние ПОРЛ - авария");
	messages["prl@obSost"].setMessage("*:error", "error", "АСКУ", "Общее состояние ПОРЛ - неисправность");
	messages["prl@obSost"].setMessage("avar,error:norma", "norma", "АСКУ", "Общее состояние ПОРЛ - норма");

	messages["vrl@obSost"].setMessage("*:not", "simple", "АСКУ", "Общее состояние МВРЛ-КН - отключен");
	messages["vrl@obSost"].setMessage("*:avar", "avar", "АСКУ", "Общее состояние МВРЛ-КН - авария");
	messages["vrl@obSost"].setMessage("*:error", "error", "АСКУ", "Общее состояние МВРЛ-КН - неисправность");
	messages["vrl@obSost"].setMessage("avar,error:norma", "norma", "АСКУ", "Общее состояние МВРЛ-КН - норма");

	messages["urlk@obSost"].setMessage("*:not", "not", "АСКУ", "Общее состояние УРЛК - отключен");
	messages["urlk@obSost"].setMessage("*:avar", "avar", "АСКУ", "Общее состояние УРЛК - авария");
	messages["urlk@obSost"].setMessage("*:error", "error", "АСКУ", "Общее состояние УРЛК - неисправность");
	messages["urlk@obSost"].setMessage("avar,error:norma", "norma", "АСКУ", "Общее состояние УРЛК - норма");
}

// ----------------------------------------------------------------------------
